dist: bionic
language: ruby
cache: bundler
before_install:
- bundle -v
- rm -f Gemfile.lock
- gem update --system $RUBYGEMS_VERSION
- gem --version
- bundle -v
script:
- bundle exec rake $CHECK
rvm:
- 2.5.3
stages:
- static
- spec
- name: deploy
  if: tag =~ ^v\d
jobs:
  fast_finish: true
  include:
  - stage: static
    bundler_args: "--without system_tests"
    env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"

  - stage: spec
    bundler_args: "--without system_tests"
    env: PUPPET_GEM_VERSION="~> 6.0" CHECK="parallel_spec spec/classes spec/defines"

  - stage: deploy
    bundler_args: "--without system_tests"
    env: CHECK=build DEPLOY_TO_FORGE=yes

branches:
  only:
  - master
  - "/^v\\d/"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: maeq
  password:
    secure: "KlQPtOCBjD2goyYcQSQND7lQzK7zqPsGV8a6avZQQytis9//h7aeYxcjMciDZhw+uJ1dnasumuC5xFT6OCZeXH1cRPb0M/I9JJkfSy5lY8NFLWkUe6Eb3MFqMJI1We5Eh6nUvmQS1OkmgUtdg9KllR+4XWwy5BA9YoDWXmQIHqsC4YCZKUlq88UXhFzfPPIkt/F2I+txV/tNsEW6B2JhiDawvuQjF8pvkyXQDGfhEYjEBY7uTRXhXkgtDopmTsxhILZ3ia10SOHtaUHss6G5fZydxlTA/ahn9iDKfPYD/lQnx6Uhu4l3Tde8xnZ93Kq/Q5GuxCvf4ikvd5qmOnVk1ou31jfrN8U88uPpTG8ximDBvuiggZhoyili+1l7+fq0ipjBrbzcR1kswxRqu4264ngtgPVixW+qwSvM/rcAub23md+vrlFyii+YthHV4AIGJqkx403cRIlH3hy5grymBzZSXDkxDt+XOjGwu/Vw35VSZbgKINPctHNJSzBfUX+6kbaNuEz5Rpl16bbc5LXmL17WXXbTz175SF223La6KRh4m5HZ0QiYlRLfICrFUaZrSxXC5nBJqkCcQGAVYp7xBgi5WJGQo6sew6MD7pS09TGP2+Z+CTF1lXFAKn8yB+3echaO84i5uuAKC0jBpMGOIEkQglQ6EmynGRx7kHsjfaA="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
